"""empty message

Revision ID: 447437152b5e
Revises: 
Create Date: 2019-09-08 15:22:27.837436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447437152b5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sell', sa.Integer(), nullable=True),
    sa.Column('List', sa.Integer(), nullable=True),
    sa.Column('Living', sa.Integer(), nullable=True),
    sa.Column('Rooms', sa.Integer(), nullable=True),
    sa.Column('Beds', sa.Integer(), nullable=True),
    sa.Column('Baths', sa.Integer(), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Acres', sa.Float(), nullable=True),
    sa.Column('Taxes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home')
    # ### end Alembic commands ###
