"""empty message

Revision ID: bf2d3d4d3d5a
Revises: 447437152b5e
Create Date: 2019-09-13 09:57:43.822174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2d3d4d3d5a'
down_revision = '447437152b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sell', sa.Integer(), nullable=True),
    sa.Column('List', sa.Integer(), nullable=True),
    sa.Column('Living', sa.Integer(), nullable=True),
    sa.Column('Rooms', sa.Integer(), nullable=True),
    sa.Column('Beds', sa.Integer(), nullable=True),
    sa.Column('Baths', sa.Integer(), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Acres', sa.Float(), nullable=True),
    sa.Column('Taxes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home')
    # ### end Alembic commands ###
